
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lcluwsgovzrhkykccrwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjbHV3c2dvdnpyaGt5a2NjcndmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MTQyNTMsImV4cCI6MjA2MjE5MDI1M30.gF-HU9MkllgRgrCUwZMPZkAmZ_impsWNLcR8Q0vQhWk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  }
});
